version: '3'
services:
  stocks-backend:
    image: stocks-backend:1.0
    build: .
    restart: on-failure
    env_file: .env
    environment: 
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on: 
      - db
  db:
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbdata:/data/db
    image: mysql
    restart: always
    env_file: .env
    environment: 
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
    ports: 
      - '3306:3306'
    networks:
      - app-network
volumes:
  dbdata:
networks:
  app-network:
    driver: bridge
