version: '3'
services:
  stocks-backend:
    image: gcr.io/omar-0/stocks-backend:1.0
    build: .
    restart: on-failure
    env_file: .env
    environment: 
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on: 
      - mysql
  mysql:
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbdata:/data/db
    image: mysql
    restart: always
    env_file: .env
    environment: 
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
    ports: 
      - '3306:3306'
    networks:
      - app-network
volumes:
  dbdata:
networks:
  app-network:
    driver: bridge
